// Mock data for DailyMarts — Milk & Dairy Focused Agricultural Marketplace

export const mockFarmers = [
  {
    id: 'F001',
    name: 'Ravi Kumar',
    farm: 'Ravi Dairy Farm',
    location: 'Dindigul',
    distance: '2.3 km',
    rating: 4.9,
    phone: '9876543210',
    email: 'ravi@ravifarm.com',
    categories: ['milk', 'dairy'],
    dairyCows: 28,
    dailyMilkYield: '140 L',
    purityCertified: true,
    fatAverage: '4.8%',
    image: null,
    verified: true,
  },
  {
    id: 'F002',
    name: 'Suresh Pandi',
    farm: 'Green Valley Organic Farm',
    location: 'Madurai',
    distance: '5.1 km',
    rating: 4.7,
    phone: '9876543211',
    email: 'suresh@gvfarm.com',
    categories: ['milk', 'vegetables', 'dairy'],
    dairyCows: 18,
    dailyMilkYield: '90 L',
    purityCertified: true,
    fatAverage: '4.2%',
    image: null,
    verified: true,
  },
  {
    id: 'F003',
    name: 'Meena Devi',
    farm: 'Sunrise Dairy & Livestock',
    location: 'Coimbatore',
    distance: '8.4 km',
    rating: 4.8,
    phone: '9876543212',
    email: 'meena@sunrise.com',
    categories: ['milk', 'chicken', 'meat'],
    dairyCows: 22,
    dailyMilkYield: '110 L',
    purityCertified: true,
    fatAverage: '6.5% (Buffalo)',
    image: null,
    verified: true,
  },
  {
    id: 'F004',
    name: 'Arjun Pillai',
    farm: 'Pillai A2 Gir Cow Farm',
    location: 'Tirunelveli',
    distance: '12.0 km',
    rating: 4.9,
    phone: '9876543213',
    email: 'arjun@pillai.com',
    categories: ['milk', 'dairy'],
    dairyCows: 35,
    dailyMilkYield: '160 L',
    purityCertified: true,
    fatAverage: '4.9% (A2 Milk)',
    image: null,
    verified: true,
  },
];

export const mockProducts = [
  {
    id: 'DM-MILK-001',
    name: 'Pure Fresh Cow Milk',
    category: 'milk',
    emoji: '🥛',
    farmerId: 'F001',
    farmerName: 'Ravi Kumar',
    farmName: 'Ravi Dairy Farm',
    location: 'Dindigul',
    price: 60,
    unit: 'L',
    fatContent: '4.2% Fat',
    snfContent: '8.5% SNF',
    milkingSlot: '4:30 AM Morning Milking',
    packaging: 'Eco Glass Bottle / Sealed Pouch',
    availableCapacity: 35,
    totalCapacity: 60,
    soldCapacity: 25,
    description: '100% natural, farm-fresh cow milk collected every morning at 4:30 AM. Chilled immediately to 4°C. Zero preservatives, unadulterated, and delivered to your door before 7:00 AM.',
    rating: 4.9,
    reviewCount: 248,
    status: 'available',
    isOrganic: true,
    isA2: false,
    tags: ['fresh', 'daily-milk', 'chilled-4C', 'untouched'],
  },
  {
    id: 'DM-MILK-002',
    name: 'A2 Native Gir Cow Milk',
    category: 'milk',
    emoji: '🥛',
    farmerId: 'F004',
    farmerName: 'Arjun Pillai',
    farmName: 'Pillai A2 Gir Cow Farm',
    location: 'Tirunelveli',
    price: 85,
    unit: 'L',
    fatContent: '4.8% Fat',
    snfContent: '9.0% SNF',
    milkingSlot: '4:00 AM Vedic Milking',
    packaging: 'Sterilized Glass Bottle',
    availableCapacity: 20,
    totalCapacity: 45,
    soldCapacity: 25,
    description: 'Pure A2 Beta-Casein milk from indigenous Gir cows fed on organic pasture fields. Highly digestible, rich in immunity boosters, and free from synthetic hormones.',
    rating: 5.0,
    reviewCount: 189,
    status: 'available',
    isOrganic: true,
    isA2: true,
    tags: ['A2-beta-casein', 'gir-cow', 'digestible', 'glass-bottle'],
  },
  {
    id: 'DM-MILK-003',
    name: 'Creamy Buffalo Milk',
    category: 'milk',
    emoji: '🥛',
    farmerId: 'F003',
    farmerName: 'Meena Devi',
    farmName: 'Sunrise Dairy & Livestock',
    location: 'Coimbatore',
    price: 75,
    unit: 'L',
    fatContent: '7.2% High Fat',
    snfContent: '9.5% SNF',
    milkingSlot: '5:00 AM Milking',
    packaging: 'Food-grade Sealed Pouch',
    availableCapacity: 15,
    totalCapacity: 35,
    soldCapacity: 20,
    description: 'Rich, high-fat buffalo milk ideal for thick curd, traditional paneer, homemade khoa, and delicious milk sweets. Delivered fresh twice daily.',
    rating: 4.8,
    reviewCount: 142,
    status: 'available',
    isOrganic: false,
    isA2: false,
    tags: ['high-fat', 'creamy', 'thick-curd', 'sweet-making'],
  },
  {
    id: 'DM-DAI-001',
    name: 'Traditional Bilona Cow Ghee',
    category: 'dairy',
    emoji: '🧈',
    farmerId: 'F001',
    farmerName: 'Ravi Kumar',
    farmName: 'Ravi Dairy Farm',
    location: 'Dindigul',
    price: 750,
    unit: '500g',
    fatContent: '99.8% Pure Milk Fat',
    snfContent: 'Bilona Churned',
    milkingSlot: 'Handcrafted Batch',
    packaging: 'Glass Jar',
    availableCapacity: 10,
    totalCapacity: 20,
    soldCapacity: 10,
    description: 'Golden granular ghee prepared using traditional wooden churners (Bilona method) from curd made of pure cow milk. Nutritious, rich aroma, and authentic taste.',
    rating: 4.9,
    reviewCount: 115,
    status: 'available',
    isOrganic: true,
    isA2: false,
    tags: ['bilona-churned', 'golden-ghee', 'pure-cow-fat'],
  },
  {
    id: 'DM-DAI-002',
    name: 'Fresh Farm Cottage Cheese (Paneer)',
    category: 'dairy',
    emoji: '🧀',
    farmerId: 'F001',
    farmerName: 'Ravi Kumar',
    farmName: 'Ravi Dairy Farm',
    location: 'Dindigul',
    price: 160,
    unit: '250g',
    fatContent: 'Full Cream',
    snfContent: 'Soft & Fresh',
    milkingSlot: 'Morning Batch',
    packaging: 'Vacuum Sealed Pack',
    availableCapacity: 12,
    totalCapacity: 25,
    soldCapacity: 13,
    description: 'Super soft, fresh paneer made from pure whole cow milk lemon curdling. High protein, melt-in-mouth texture with zero starch or artificial thickeners.',
    rating: 4.7,
    reviewCount: 96,
    status: 'available',
    isOrganic: true,
    isA2: false,
    tags: ['soft-paneer', 'high-protein', 'no-starch'],
  },
  {
    id: 'DM-DAI-003',
    name: 'Thick Farm Set Curd (Dahi)',
    category: 'dairy',
    emoji: '🏺',
    farmerId: 'F002',
    farmerName: 'Suresh Pandi',
    farmName: 'Green Valley Organic Farm',
    location: 'Madurai',
    price: 45,
    unit: '500g',
    fatContent: 'Natural Culture',
    snfContent: 'Thick Set',
    milkingSlot: 'Earthen Pot Set',
    packaging: 'Clay Matka / Container',
    availableCapacity: 25,
    totalCapacity: 40,
    soldCapacity: 15,
    description: 'Thick, creamy curd naturally fermented in clay matkas using traditional natural lactobacillus cultures. Refreshing, gut-friendly, and naturally sweet.',
    rating: 4.8,
    reviewCount: 88,
    status: 'available',
    isOrganic: true,
    isA2: false,
    tags: ['matka-curd', 'probiotic', 'natural-culture'],
  },
  {
    id: 'DM-VEG-001',
    name: 'Organic Farm Tomatoes',
    category: 'vegetables',
    emoji: '🍅',
    farmerId: 'F002',
    farmerName: 'Suresh Pandi',
    farmName: 'Green Valley Organic Farm',
    location: 'Madurai',
    price: 40,
    unit: 'kg',
    fatContent: 'N/A',
    snfContent: 'Pesticide Free',
    milkingSlot: 'Morning Harvest',
    packaging: 'Eco Mesh Bag',
    availableCapacity: 50,
    totalCapacity: 80,
    soldCapacity: 30,
    description: 'Freshly harvested vine-ripened organic tomatoes. Rich in lycopene and antioxidants.',
    rating: 4.6,
    reviewCount: 76,
    status: 'available',
    isOrganic: true,
    isA2: false,
    tags: ['organic', 'fresh-harvest'],
  },
  {
    id: 'DM-CHK-001',
    name: 'Fresh Country Chicken',
    category: 'chicken',
    emoji: '🐔',
    farmerId: 'F003',
    farmerName: 'Meena Devi',
    farmName: 'Sunrise Dairy & Livestock',
    location: 'Coimbatore',
    price: 320,
    unit: 'kg',
    fatContent: 'N/A',
    snfContent: 'Antibiotic Free',
    milkingSlot: 'Cleaned on Order',
    packaging: 'Chilled Hygienic Pack',
    availableCapacity: 18,
    totalCapacity: 30,
    soldCapacity: 12,
    description: 'Free-range country chicken raised on natural grain diets. Antibiotic and hormone-free.',
    rating: 4.9,
    reviewCount: 203,
    status: 'available',
    isOrganic: true,
    isA2: false,
    tags: ['free-range', 'antibiotic-free'],
  },
];

export const mockOrders = [
  {
    id: 'ORD-MILK-2026-001',
    productId: 'DM-MILK-001',
    productName: 'Pure Fresh Cow Milk',
    productEmoji: '🥛',
    farmerId: 'F001',
    farmerName: 'Ravi Kumar (Ravi Dairy)',
    quantity: 1,
    unit: 'L',
    frequency: 'daily',
    deliveryTime: 'morning',
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    pricePerUnit: 60,
    totalDays: 31,
    totalAmount: 1860,
    paidAmount: 1200,
    remainingAmount: 660,
    paymentStatus: 'partial',
    orderStatus: 'active',
    nextDelivery: '2026-08-23 (Morning 6:30 AM)',
  },
  {
    id: 'ORD-MILK-2026-002',
    productId: 'DM-MILK-002',
    productName: 'A2 Native Gir Cow Milk',
    productEmoji: '🥛',
    farmerId: 'F004',
    farmerName: 'Arjun Pillai (A2 Farm)',
    quantity: 1,
    unit: 'L',
    frequency: 'daily',
    deliveryTime: 'morning',
    startDate: '2026-08-10',
    endDate: '2026-09-09',
    pricePerUnit: 85,
    totalDays: 30,
    totalAmount: 2550,
    paidAmount: 2550,
    remainingAmount: 0,
    paymentStatus: 'paid',
    orderStatus: 'active',
    nextDelivery: '2026-08-23 (Morning 6:15 AM)',
  },
  {
    id: 'ORD-DAI-2026-003',
    productId: 'DM-DAI-001',
    productName: 'Traditional Bilona Cow Ghee',
    productEmoji: '🧈',
    farmerId: 'F001',
    farmerName: 'Ravi Kumar',
    quantity: 1,
    unit: '500g',
    frequency: 'once',
    deliveryTime: null,
    startDate: '2026-08-15',
    endDate: null,
    pricePerUnit: 750,
    totalDays: 1,
    totalAmount: 750,
    paidAmount: 750,
    remainingAmount: 0,
    paymentStatus: 'paid',
    orderStatus: 'completed',
    nextDelivery: null,
  },
];

export const mockBills = [
  {
    id: 'BILL-2026-AUG-MILK',
    invoiceNo: 'INV-DM-2026-0891',
    orderId: 'ORD-MILK-2026-001',
    productName: 'Pure Fresh Cow Milk Subscription (1L Daily)',
    farmerName: 'Ravi Kumar (Ravi Dairy Farm)',
    period: 'August 2026',
    quantity: 1,
    unit: 'L',
    days: 31,
    pricePerUnit: 60,
    subtotal: 1860,
    discount: 0,
    totalAmount: 1860,
    paidAmount: 1200,
    remainingAmount: 660,
    dueDate: '2026-08-31',
    paymentStatus: 'partial',
    transactions: [
      { id: 'TXN-MILK-01', date: '2026-08-01', amount: 600, mode: 'UPI (GPay)', ref: 'UPI984210' },
      { id: 'TXN-MILK-02', date: '2026-08-12', amount: 600, mode: 'UPI (PhonePe)', ref: 'UPI881240' },
    ],
  },
];

export const mockNotifications = [
  { id: 'N001', type: 'delivery', title: '🥛 Morning Milk Dispatched!', message: 'Ravi Dairy Farm dispatched your 1L Fresh Cow Milk. Delivery expected by 6:30 AM.', time: '2026-08-22T06:05:00', read: false, icon: '🚚' },
  { id: 'N002', type: 'order', title: '✅ Milk Subscription Confirmed', message: 'Your A2 Gir Cow Milk daily subscription has been accepted by Arjun Pillai.', time: '2026-08-21T18:30:00', read: false, icon: '🥛' },
  { id: 'N003', type: 'payment', title: '💰 Monthly Milk Bill Reminder', message: '₹660 remaining balance for August Milk Subscription. Due Aug 31.', time: '2026-08-21T09:00:00', read: true, icon: '💳' },
];

export const mockFarmerStats = {
  todaySales: 110,
  totalSales: 3420,
  todayRevenue: 6850,
  monthlyRevenue: 184500,
  pendingPayments: 8400,
  availableProducts: 5,
  activeCustomers: 42,
  milkingBatchStatus: 'Morning Batch Chilled to 4°C',
};

export const mockFarmerOrders = [
  { id: 'ORD-C001', customerId: 'C001', customerName: 'Priya Sharma', product: 'Pure Fresh Cow Milk', quantity: 1, unit: 'L', deliveryTime: 'morning', date: '2026-08-22', amount: 60, paymentStatus: 'pending', orderStatus: 'active' },
  { id: 'ORD-C002', customerId: 'C002', customerName: 'Karthik Raja', product: 'A2 Native Gir Cow Milk', quantity: 2, unit: 'L', deliveryTime: 'morning', date: '2026-08-22', amount: 170, paymentStatus: 'paid', orderStatus: 'supplied' },
  { id: 'ORD-C003', customerId: 'C003', customerName: 'Anjali Devi', product: 'Creamy Buffalo Milk', quantity: 1, unit: 'L', deliveryTime: 'evening', date: '2026-08-22', amount: 75, paymentStatus: 'pending', orderStatus: 'active' },
  { id: 'ORD-C004', customerId: 'C004', customerName: 'Manoj Pillai', product: 'Bilona Cow Ghee', quantity: 1, unit: '500g', deliveryTime: 'morning', date: '2026-08-22', amount: 750, paymentStatus: 'paid', orderStatus: 'completed' },
];

export const mockSalesData = {
  weekly: [
    { day: 'Mon', revenue: 6200, liters: 98 },
    { day: 'Tue', revenue: 5800, liters: 92 },
    { day: 'Wed', revenue: 6600, liters: 104 },
    { day: 'Thu', revenue: 7100, liters: 112 },
    { day: 'Fri', revenue: 6900, liters: 108 },
    { day: 'Sat', revenue: 8200, liters: 130 },
    { day: 'Sun', revenue: 7800, liters: 124 },
  ],
  monthly: [
    { month: 'Jan', revenue: 145000 }, { month: 'Feb', revenue: 158000 },
    { month: 'Mar', revenue: 162000 }, { month: 'Apr', revenue: 170000 },
    { month: 'May', revenue: 175000 }, { month: 'Jun', revenue: 168000 },
    { month: 'Jul', revenue: 182000 }, { month: 'Aug', revenue: 184500 },
  ],
};

export const mockFarmerProducts = [
  { id: 'DM-MILK-001', name: 'Pure Fresh Cow Milk', category: 'milk', emoji: '🥛', totalCapacity: 60, soldCapacity: 45, price: 60, unit: 'L', status: 'available', location: 'Dindigul' },
  { id: 'DM-MILK-002', name: 'A2 Native Gir Cow Milk', category: 'milk', emoji: '🥛', totalCapacity: 45, soldCapacity: 38, price: 85, unit: 'L', status: 'available', location: 'Dindigul' },
  { id: 'DM-MILK-003', name: 'Creamy Buffalo Milk', category: 'milk', emoji: '🥛', totalCapacity: 35, soldCapacity: 30, price: 75, unit: 'L', status: 'limited', location: 'Dindigul' },
  { id: 'DM-DAI-001', name: 'Bilona Cow Ghee', category: 'dairy', emoji: '🧈', totalCapacity: 20, soldCapacity: 14, price: 750, unit: '500g', status: 'available', location: 'Dindigul' },
  { id: 'DM-DAI-002', name: 'Fresh Paneer', category: 'dairy', emoji: '🧀', totalCapacity: 25, soldCapacity: 25, price: 160, unit: '250g', status: 'sold-out', location: 'Dindigul' },
];

export const mockCustomerBilling = [
  { customerId: 'C001', name: 'Priya Sharma', product: 'Fresh Cow Milk 1L Daily (Morning)', totalAmount: 1860, paidAmount: 1200, remaining: 660, status: 'partial', lastPayment: '2026-08-12' },
  { customerId: 'C002', name: 'Karthik Raja', product: 'A2 Gir Cow Milk 1L Daily (Morning)', totalAmount: 2550, paidAmount: 2550, remaining: 0, status: 'paid', lastPayment: '2026-08-10' },
  { customerId: 'C003', name: 'Anjali Devi', product: 'Buffalo Milk 1L Daily (Evening)', totalAmount: 2325, paidAmount: 0, remaining: 2325, status: 'pending', lastPayment: null },
  { customerId: 'C004', name: 'Manoj Pillai', product: 'Bilona Ghee 500g Jar', totalAmount: 750, paidAmount: 750, remaining: 0, status: 'paid', lastPayment: '2026-08-15' },
];

export const mockExchangeRequests = [
  { id: 'EX-001', farmerId: 'F002', farmerName: 'Suresh Pandi', farmName: 'Green Valley Farm', location: 'Madurai', product: 'Fresh Cow Milk', requiredQty: 10, unit: 'L', availableQty: 0, distance: '5.1 km', requestDate: '2026-08-22', notes: 'Urgent: Morning customer demand exceeded yield by 10L.', status: 'open' },
  { id: 'EX-002', farmerId: 'F004', farmerName: 'Arjun Pillai', farmName: 'Pillai A2 Farm', location: 'Tirunelveli', product: 'A2 Gir Cow Milk', requiredQty: 5, unit: 'L', availableQty: 0, distance: '12.0 km', requestDate: '2026-08-21', notes: 'New bulk subscription order started today.', status: 'open' },
];

export const categories = [
  { id: 'milk',       name: 'Fresh Milk',      emoji: '🥛', color: '#e6f5eb' },
  { id: 'dairy',      name: 'Farm Dairy',      emoji: '🧈', color: '#fef9e6' },
  { id: 'vegetables', name: 'Organic Veggies', emoji: '🥬', color: '#e8f5e9' },
  { id: 'chicken',    name: 'Country Chicken', emoji: '🐔', color: '#fff7e6' },
  { id: 'meat',       name: 'Farm Meat',       emoji: '🥩', color: '#fde8e8' },
];

export const locations = ['All Locations', 'Dindigul', 'Madurai', 'Coimbatore', 'Tirunelveli', 'Chennai', 'Trichy'];
